/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.43
 * Generated at: 2021-04-25 15:01:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import kr.or.bit.action.Action;
import kr.or.bit.service.EmpListService;
import kr.or.bit.dto.Emp;
import java.util.List;

public final class EmpWrite_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/javax.servlet.jsp.jstl-1.2.1.jar", Long.valueOf(1618207250186L));
    _jspx_dependants.put("jar:file:/C:/Users/sh089/WEB(Back)/WebLabs/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Emp_Model2_Mvc_Team1/WEB-INF/lib/javax.servlet.jsp.jstl-1.2.1.jar!/META-INF/c.tld", Long.valueOf(1323225978000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("kr.or.bit.service.EmpListService");
    _jspx_imports_classes.add("kr.or.bit.action.Action");
    _jspx_imports_classes.add("kr.or.bit.dto.Emp");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<!--[if lt IE 7]>      <html class=\"no-js lt-ie9 lt-ie8 lt-ie7\" lang=\"\"> <![endif]-->\r\n");
      out.write("<!--[if IE 7]>         <html class=\"no-js lt-ie9 lt-ie8\" lang=\"\"> <![endif]-->\r\n");
      out.write("<!--[if IE 8]>         <html class=\"no-js lt-ie9\" lang=\"\"> <![endif]-->\r\n");
      out.write("<!--[if gt IE 8]><!-->\r\n");
      out.write("<html class=\"no-js\" lang=\"en\">\r\n");
      out.write("<!--<![endif]-->\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<!-- jQuery -->\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.3.1.slim.min.js\"\r\n");
      out.write("\tintegrity=\"sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo\"\r\n");
      out.write("\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap CSS -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css\"\r\n");
      out.write("\tintegrity=\"sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS\"\r\n");
      out.write("\tcrossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>Sufee Admin - HTML5 Admin Template</title>\r\n");
      out.write("<meta name=\"description\" content=\"Sufee Admin - HTML5 Admin Template\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"apple-touch-icon\" href=\"apple-icon.png\">\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"favicon.ico\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"vendors/bootstrap/dist/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"vendors/font-awesome/css/font-awesome.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"vendors/themify-icons/css/themify-icons.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"vendors/flag-icon-css/css/flag-icon.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"vendors/selectFX/css/cs-skin-elastic.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"vendors/jqvmap/dist/jqvmap.min.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/style.css\">\r\n");
      out.write("\r\n");
      out.write("<link\r\n");
      out.write("\thref='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700,800'\r\n");
      out.write("\trel='stylesheet' type='text/css'>\r\n");
      out.write("\r\n");
      out.write("<!-- 게시판 디자인 -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://use.fontawesome.com/releases/v5.7.0/css/all.css\"\r\n");
      out.write("\tintegrity=\"sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ\"\r\n");
      out.write("\tcrossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("tr>th {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write(".divtag {\r\n");
      out.write("\tpadding-top: 70px;\r\n");
      out.write("\tpadding-bottom: 30px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Left Panel -->\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/common/LeftMenu.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- /Left Panel -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- Right Panel -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"right-panel\" class=\"right-panel\">\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Header-->\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/common/TopMenu.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t<!-- /Header -->\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"breadcrumbs\">\r\n");
      out.write("\t\t\t<div class=\"col-sm-4\">\r\n");
      out.write("\t\t\t\t<div class=\"page-header float-left\">\r\n");
      out.write("\t\t\t\t\t<div class=\"page-title\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<h1>회원 등록 테이블</h1>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-sm-8\">\r\n");
      out.write("\t\t\t\t<div class=\"page-header float-right\">\r\n");
      out.write("\t\t\t\t\t<div class=\"page-title\">\r\n");
      out.write("\t\t\t\t\t\t<ol class=\"breadcrumb text-right\">\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"active\">회원 등록 테이블</li>\r\n");
      out.write("\t\t\t\t\t\t</ol>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<article>\r\n");
      out.write("\t\t\t<div class=\"container\" role=\"main\">\r\n");
      out.write("\t\t\t\t<h2>사원 등록</h2>\r\n");
      out.write("\t\t\t\t<form name=\"form\" id=\"form\" role=\"form\" method=\"post\"\r\n");
      out.write("\t\t\t\t\taction=\"EmpWriteok.do\" enctype=\"multipart/form-data\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"mb-3\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"title\">사진 등록</label> <br> \r\n");
      out.write("\t\t\t \t\t<img id=\"preview\" src=\"upload/emp.jpg\" width=\"300\" alt=\"로컬에 있는 이미지가 보여지는 영역\">\t\r\n");
      out.write("\t\t\t\t\t<input type=\"file\" id=\"fileName\" name=\"fileName\" class=\"fileName\" accept=\"image/*\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"mb-3\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"title\">사원 번호</label> \r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"form-control\" name=\"empno\" id=\"empno\"\r\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"ex) 2161\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"mb-3\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"reg_id\">사원 이름</label> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"form-control\" name=\"ename\" id=\"ename\"\r\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"ex) SMITH\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"mb-3\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"reg_id\">사원 직종</label> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"form-control\" name=\"job\" id=\"job\"\r\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"ex) SALESMAN\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"mb-3\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"reg_id\">관리자 번호</label> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"form-control\" name=\"mgr\" id=\"mgr\" placeholder=\"ex) 9141\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"mb-3\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"reg_id\">입사일</label> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"form-control\" name=\"hiredate\" id=\"hiredate\"\r\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"ex) 19940405\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"mb-3\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"reg_id\">급여</label> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"form-control\" name=\"sal\" id=\"sal\" placeholder=\"ex) 1600\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"mb-3\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"reg_id\">커미션</label> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"form-control\" name=\"comm\" id=\"comm\" placeholder=\"ex) 300\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"mb-3\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"reg_id\">부서번호</label> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"form-control\" name=\"deptno\" id=\"deptno\"\r\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"ex) 20\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<!-- <button type=\"button\" class=\"btn btn-sm btn-primary\" id=\"btnSave\">저장</button> -->\r\n");
      out.write("\t\t\t\t\t<!-- <button type=\"button\" class=\"btn btn-sm btn-primary\" id=\"btnSave\">저장</button>  -->\r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" class=\"btn btn-sm btn-primary\" value=\"저장\">\r\n");
      out.write("\t\t\t\t\t\t<!-- <a href=\"delete.do?empno=7369\" type=\"button\" class=\"btn btn-sm btn-primary\">삭제</a> -->\r\n");
      out.write("\t\t\t\t\t\t<a href=\"EmpTable.do\" type=\"button\" class=\"btn btn-sm btn-primary\">목록</a>\r\n");
      out.write("\t\t\t\t\t\t<!--  <bautton type=\"button\" class=\"btn btn-sm btn-primary\" id=\"btnList\" onclick=\"location.href='emplist.jsp'\">목록</button> -->\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</article>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- .content -->\r\n");
      out.write("\r\n");
      out.write("<!-- /#right-panel -->\r\n");
      out.write("\r\n");
      out.write("<!-- Right Panel -->\r\n");
      out.write("\r\n");
      out.write("<script src=\"vendors/jquery/dist/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"vendors/popper.js/dist/umd/popper.min.js\"></script>\r\n");
      out.write("<script src=\"vendors/bootstrap/dist/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"assets/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"vendors/chart.js/dist/Chart.bundle.min.js\"></script>\r\n");
      out.write("<script src=\"assets/js/dashboard.js\"></script>\r\n");
      out.write("<script src=\"assets/js/widgets.js\"></script>\r\n");
      out.write("<script src=\"vendors/jqvmap/dist/jquery.vmap.min.js\"></script>\r\n");
      out.write("<script src=\"vendors/jqvmap/examples/js/jquery.vmap.sampledata.js\"></script>\r\n");
      out.write("<script src=\"vendors/jqvmap/dist/maps/jquery.vmap.world.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("   (function($) {\r\n");
      out.write("      \"use strict\";\r\n");
      out.write("      \r\n");
      out.write("      $(document).on('click', '#btnSave', function(e) {\r\n");
      out.write("          e.preventDefault();\r\n");
      out.write("          $(\"#form\").submit();\r\n");
      out.write("       });\r\n");
      out.write("      jQuery('#vmap').vectorMap({\r\n");
      out.write("         map : 'world_en',\r\n");
      out.write("         backgroundColor : null,\r\n");
      out.write("         color : '#ffffff',\r\n");
      out.write("         hoverOpacity : 0.7,\r\n");
      out.write("         selectedColor : '#1de9b6',\r\n");
      out.write("         enableZoom : true,\r\n");
      out.write("         showTooltip : true,\r\n");
      out.write("         values : sample_data,\r\n");
      out.write("         scaleColors : [ '#1de9b6', '#03a9f5' ],\r\n");
      out.write("         normalizeFunction : 'polynomial'\r\n");
      out.write("      });\r\n");
      out.write("      \r\n");
      out.write("      $(document).on('click', '#upload', function(e) {\r\n");
      out.write("   \t   console.log($(\"#fileName\").val());\r\n");
      out.write("                  $.ajax({\r\n");
      out.write("                     url : \"upload.do\",\r\n");
      out.write("                     type : 'POST',\r\n");
      out.write("                     dataType : \"json\",\r\n");
      out.write("                     data : {\r\n");
      out.write("                        filename : $(\"#fileName\").val()\r\n");
      out.write("                     },\r\n");
      out.write("                     success : function(data) {\r\n");
      out.write("                   \t  \r\n");
      out.write("                        }\r\n");
      out.write("                     });\r\n");
      out.write("            })\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            var file = document.querySelector('#fileName');\r\n");
      out.write("\r\n");
      out.write("      file.onchange = function () { \r\n");
      out.write("          var fileList = file.files ;\r\n");
      out.write("          \r\n");
      out.write("          // 읽기\r\n");
      out.write("          var reader = new FileReader();\r\n");
      out.write("          reader.readAsDataURL(fileList [0]);\r\n");
      out.write("\r\n");
      out.write("          //로드 한 후\r\n");
      out.write("          reader.onload = function  () {\r\n");
      out.write("              document.querySelector('#preview').src = reader.result ;\r\n");
      out.write("          }; \r\n");
      out.write("      }; \r\n");
      out.write("      \r\n");
      out.write("   })(jQuery);\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
